name: LinksaberFridayDigestV1

on:
  schedule:
    # UTC time: -2 hours wrt Rome/IT
#    - cron:  '0 15 * * 5'
    - cron:  '10 15 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Linksaber - V1 - Trigger Friday Digest
       run: curl -s -X GET $FCF_HOST/api/v1/users/sendMail/weekly
       env:
        FCF_HOST: ${{ secrets.FCF_HOST }}
