name: LinksaberFridayDigestV1

on:
  schedule:
    # UTC time: -2 hours wrt Rome/IT
    # debug: https://crontab.guru/#0_0/1_*_*_5
    - cron:  '0 0/1 * * 5'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Linksaber - V1 - Trigger Friday Digest
       run: curl -s -X GET $FCF_HOST/api/v1/users/sendMail/weekly/debug
       env:
        FCF_HOST: ${{ secrets.FCF_HOST }}
