name: LinksaberFridayDigestV1

on:
  schedule:
    - cron:  '0 17 * * 5'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Linksaber - V1 - Trigger Friday Digest
       run: curl -s -X POST $FCF_HOST/api/v1/users/sendMail/weekly
       env:
        FCF_HOST: ${{ secrets.FCF_HOST }}
